<?php

namespace App\Services;

class PortfolioService
{
    public static function all(): array
    {
        return self::projects();
    }

    public static function categories(): array
    {
        $cats = [];
        foreach (self::projects() as $p) {
            $cats[$p['category']] = ($cats[$p['category']] ?? 0) + 1;
        }
        ksort($cats);
        return $cats;
    }

    public static function find(string $slug): ?array
    {
        foreach (self::projects() as $p) {
            if ($p['slug'] === $slug) {
                return $p;
            }
        }
        return null;
    }

    /**
     * 28 real production projects shipped by Khaled Ahmed.
     * Curated from live deployments — duplicates removed.
     */
    private static function projects(): array
    {
        return [
            [
                'slug' => 'barmagly-tech',
                'title' => 'Barmagly — Swiss-Licensed Software House',
                'summary' => 'Founder & lead developer. Enterprise web, mobile, POS and business automation systems delivered to clients across Europe and the Middle East.',
                'category' => 'Tech / SaaS',
                'tech' => ['Laravel', 'Next.js', 'Node.js', 'TypeScript', 'PostgreSQL'],
                'url' => 'https://barmagly.tech',
                'image' => 'projects/barmagly-tech.jpg',
                'role' => 'Founder, Architect, Lead Developer',
                'language' => 'en',
                'featured' => true,
            ],
            [
                'slug' => 'barmagly-pos',
                'title' => 'Barmagly POS — Cloud Multi-Tenant Cash System',
                'summary' => 'Cloud-based, multi-tenant point-of-sale system for restaurants, cafés and retail. Built for the German and Swiss markets.',
                'category' => 'Tech / SaaS',
                'tech' => ['Laravel', 'Vue.js', 'MySQL', 'Redis', 'Stripe'],
                'url' => 'https://pos.barmagly.tech',
                'image' => 'projects/barmagly-pos.jpg',
                'role' => 'Lead Developer',
                'language' => 'de',
                'featured' => true,
            ],
            [
                'slug' => 'barmagly-salon',
                'title' => 'Barmagly Salon — AI-Powered Salon Management',
                'summary' => 'SaaS platform for salons: bookings, POS, inventory, staff scheduling, AI hair-makeover previews and analytics — all in one platform.',
                'category' => 'Tech / SaaS',
                'tech' => ['Laravel', 'React', 'AI/OpenAI', 'PostgreSQL'],
                'url' => 'https://barber.barmagly.tech',
                'image' => 'projects/barmagly-salon.jpg',
                'role' => 'Lead Developer',
                'language' => 'en',
                'featured' => true,
            ],
            [
                'slug' => 'amanlaw',
                'title' => 'Aman Law — Swiss-Managed Legal Platform',
                'summary' => 'Swiss-managed legal platform connecting Syrian and Swiss lawyers with international clients across multiple practice areas.',
                'category' => 'Law Firm',
                'tech' => ['Laravel', 'Inertia.js', 'React', 'MySQL'],
                'url' => 'https://amanlaw.ch',
                'image' => 'projects/amanlaw.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'swissbridge-academy',
                'title' => 'Swiss Bridge Academy — E-Learning Platform',
                'summary' => 'Swiss-managed e-learning academy teaching programming, AI, design, marketing and sales — full LMS with student dashboards.',
                'category' => 'Education',
                'tech' => ['Laravel', 'Livewire', 'Tailwind', 'MySQL'],
                'url' => 'https://swissbridgeacademy.com',
                'image' => 'projects/swissbridge-academy.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'mossodor',
                'title' => 'Mossodor — UK Premium Lighting Store',
                'summary' => 'UK e-commerce retailer specializing in premium chandeliers, pendant lighting and wall sconces with free delivery.',
                'category' => 'E-commerce',
                'tech' => ['Shopify', 'Liquid', 'Custom Theme'],
                'url' => 'https://mossodor.com',
                'image' => 'projects/mossodor.jpg',
                'role' => 'Lead Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'shoppex-silverback',
                'title' => 'SilverBack by Shoppex — Orthopedic E-Store',
                'summary' => 'Direct-to-consumer e-commerce brand selling orthopedic seat and footrest cushions for back pain relief.',
                'category' => 'E-commerce',
                'tech' => ['Shopify', 'JavaScript', 'Custom CSS'],
                'url' => 'https://shoppex.xappee.com',
                'image' => 'projects/shoppex-silverback.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'xappee',
                'title' => 'Xappee — E-Commerce Fulfillment Platform',
                'summary' => 'E-commerce fulfillment, sourcing, digital marketing and virtual assistant services for online sellers worldwide.',
                'category' => 'Tech / SaaS',
                'tech' => ['WordPress', 'WooCommerce', 'Custom Plugins'],
                'url' => 'https://xappee.com',
                'image' => 'projects/xappee.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'ant-assist',
                'title' => 'Ant Assist — UK Virtual Assistant Agency',
                'summary' => 'UK virtual assistant agency providing offshore admin and marketing support staff to UK businesses and entrepreneurs.',
                'category' => 'Marketing',
                'tech' => ['WordPress', 'Custom Theme', 'PHP'],
                'url' => 'https://ant-assist.com',
                'image' => 'projects/ant-assist.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'rasa-lichfield',
                'title' => 'Rasa Lichfield — Halal Pan-Asian Restaurant',
                'summary' => 'UK halal Pan-Asian restaurant inside the historic Corn Exchange, blending modern Asian cooking with reservations and online ordering.',
                'category' => 'Restaurant',
                'tech' => ['WordPress', 'WooCommerce', 'Custom Theme'],
                'url' => 'https://rasalichfield.co.uk',
                'image' => 'projects/rasa-lichfield.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'kingkebab',
                'title' => 'King Kebab Le Pouzin — French Restaurant Site',
                'summary' => 'Authentic halal kebab restaurant in Le Pouzin, France — serving tacos, burgers and online delivery to local clientele.',
                'category' => 'Restaurant',
                'tech' => ['Laravel', 'Tailwind', 'MySQL'],
                'url' => 'https://kingkebablepouzin.fr',
                'image' => 'projects/kingkebab.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'fr',
            ],
            [
                'slug' => 'bnbatiment',
                'title' => 'BN Bâtiment — French Roofing Company',
                'summary' => 'Professional roofing company in Lyon, Saint-Étienne and Valence offering installation, repair and 24/7 emergency service.',
                'category' => 'Construction',
                'tech' => ['Laravel', 'Inertia.js', 'React', 'MySQL'],
                'url' => 'https://bnbatiment.com',
                'image' => 'projects/bnbatiment.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'fr',
                'featured' => true,
            ],
            [
                'slug' => 'drcembaysal',
                'title' => 'Dr. Cem Baysal — Istanbul Dental Clinic',
                'summary' => 'Istanbul dental clinic specializing in implants, veneers and cosmetic dentistry — booking system and multilingual patient pages.',
                'category' => 'Healthcare',
                'tech' => ['WordPress', 'Elementor', 'Custom CSS'],
                'url' => 'https://drcembaysal.com',
                'image' => 'projects/drcembaysal.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'grandbotanicalsuite',
                'title' => 'Grand Botanical Suite — Birmingham Wedding Venue',
                'summary' => 'Premium Birmingham wedding venue offering customizable halls, catering and full event planning with online inquiry system.',
                'category' => 'Hotel / Events',
                'tech' => ['WordPress', 'Custom Theme', 'WP Forms'],
                'url' => 'https://grandbotanicalsuite.com',
                'image' => 'projects/grandbotanicalsuite.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'jovero',
                'title' => 'JOVERO — Premier Marketing & Digital Growth Agency',
                'summary' => 'Engineering enterprise-grade marketing and software solutions — full agency site with case studies and lead-gen funnels.',
                'category' => 'Marketing',
                'tech' => ['Laravel', 'Tailwind', 'Alpine.js'],
                'url' => 'https://jovero.net',
                'image' => 'projects/jovero.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'qinawy',
                'title' => 'Qinawy — Comprehensive Qena Local Directory',
                'summary' => 'Comprehensive local-business and services directory for Qena governorate, Egypt — hospitals, doctors, hotels, restaurants and more.',
                'category' => 'Marketing',
                'tech' => ['Laravel', 'Filament', 'MySQL', 'Redis'],
                'url' => 'https://qinawy.com',
                'image' => 'projects/qinawy.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'hotel-timestay',
                'title' => 'TimeStay — Hourly Hotel Booking',
                'summary' => 'Hourly hotel-room booking platform offering short-term stays from 2–12 hours with real-time availability and payment integration.',
                'category' => 'Hotel / Events',
                'tech' => ['Laravel', 'Vue.js', 'MySQL', 'Stripe'],
                'url' => 'https://hotel.khaledahmed.net',
                'image' => 'projects/hotel-timestay.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
                'featured' => true,
            ],
            [
                'slug' => 'syanatech',
                'title' => 'SyanaTech — Home Maintenance Marketplace',
                'summary' => 'Platform connecting clients with trusted licensed technicians for home maintenance — bookings, ratings, dispatch.',
                'category' => 'Tech / SaaS',
                'tech' => ['Laravel', 'Livewire', 'MySQL', 'Pusher'],
                'url' => 'https://syanatech.khaledahmed.net',
                'image' => 'projects/syanatech.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'salesman-marketing',
                'title' => 'Sales Man — STC Business Communication',
                'summary' => 'STC enterprise communication and connectivity solutions for Saudi businesses — service catalog, lead capture and CRM integration.',
                'category' => 'Marketing',
                'tech' => ['Laravel', 'Inertia.js', 'React', 'MySQL'],
                'url' => 'https://salesman.marketing',
                'image' => 'projects/salesman-marketing.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'wasiila',
                'title' => 'Wasiila — Mecca Pilgrim Services Platform',
                'summary' => 'Platform serving Mecca pilgrims with water distribution and mosque-care supplies — multi-vendor marketplace.',
                'category' => 'Religious / Quran',
                'tech' => ['Laravel', 'Livewire', 'Tailwind', 'MySQL'],
                'url' => 'https://wasiila.com',
                'image' => 'projects/wasiila.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'hadiah-umrah',
                'title' => 'Hadiah — Digital Umrah Service App',
                'summary' => 'Digital Umrah service app connecting pilgrims with sharia-qualified service providers — booking, payments and verification.',
                'category' => 'Religious / Quran',
                'tech' => ['Laravel', 'Vue.js', 'MySQL', 'Stripe'],
                'url' => 'https://hadiah.wasiila.com',
                'image' => 'projects/hadiah-umrah.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'quran-platform',
                'title' => 'Quran Reader — Free, Ad-Free Quran Platform',
                'summary' => 'Free, ad-free and tracker-free online Quran reading and recitation platform — privacy-first design.',
                'category' => 'Religious / Quran',
                'tech' => ['Laravel', 'Alpine.js', 'Tailwind'],
                'url' => 'https://quran.khaledahmed.net',
                'image' => 'projects/quran-platform.jpg',
                'role' => 'Solo Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'infinitywearsa',
                'title' => 'Infinity Wear — Professional Sportswear Brand',
                'summary' => 'Saudi manufacturer of professional sportswear and uniforms for sports teams, schools and corporations — bulk-order workflows.',
                'category' => 'E-commerce',
                'tech' => ['WordPress', 'WooCommerce', 'Custom Theme'],
                'url' => 'https://infinitywearsa.com',
                'image' => 'projects/infinitywearsa.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'standupstraight',
                'title' => 'Stand Up Straight — UK Posture Brand',
                'summary' => 'UK posture and back-care wellness brand — direct-to-consumer e-commerce with educational content and testimonials.',
                'category' => 'E-commerce',
                'tech' => ['Shopify', 'Liquid', 'Custom Theme'],
                'url' => 'https://standupstraight.co.uk',
                'image' => 'projects/standupstraight.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
            [
                'slug' => 'gamestreet-q8',
                'title' => 'Game Street Kuwait — Gaming E-Commerce',
                'summary' => 'Kuwaiti retailer of video games, gaming consoles, accessories and PC peripherals — bilingual store with local payments.',
                'category' => 'E-commerce',
                'tech' => ['WordPress', 'WooCommerce', 'Arabic Localization'],
                'url' => 'https://gamestreetq8.com',
                'image' => 'projects/gamestreet-q8.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'bankelarb',
                'title' => 'Bank El Arab — Arabic Financial Aid Guide',
                'summary' => 'Arabic guide to instant financial-aid programs and charitable services across Arab countries — content directory.',
                'category' => 'Marketing',
                'tech' => ['WordPress', 'Custom Theme', 'Arabic SEO'],
                'url' => 'https://bankelarb.net',
                'image' => 'projects/bankelarb.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'services-researcher',
                'title' => 'Services Researcher — Academic Consultation',
                'summary' => 'Academic research, translation and statistical analysis services for graduate students — order workflow and consultation booking.',
                'category' => 'Education',
                'tech' => ['WordPress', 'Custom Theme', 'WP Forms'],
                'url' => 'https://servicesresearcher.com',
                'image' => 'projects/services-researcher.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'ar',
            ],
            [
                'slug' => 'marketing-agency-demo',
                'title' => 'Marketing Agency — Digital Marketing Site',
                'summary' => 'Digital marketing and IT solutions agency demo for startups and enterprises — service catalog with case studies.',
                'category' => 'Marketing',
                'tech' => ['Laravel', 'Tailwind', 'Alpine.js'],
                'url' => 'https://marketing.khaledahmed.net',
                'image' => 'projects/marketing-agency-demo.jpg',
                'role' => 'Full Stack Developer',
                'language' => 'en',
            ],
        ];
    }
}
