<?php

namespace App\Services;

/**
 * Dimensions of the generated project screenshots.
 *
 * The card frames a screenshot at a fixed aspect ratio and pans the image
 * through it. The pan distance is (image height - frame height), which the CSS
 * expresses as a percentage of the image's own height — so the ratio has to be
 * known when the HTML is written, not measured in the browser afterwards.
 *
 * Generated by scratchpad/process_shots.py. Do not hand-edit: rerun the script.
 */
class ScreenshotService
{
    /** Frame aspect ratios (height / width). */
    public const FRAME_SITE = 0.625;   // 16:10
    public const FRAME_APP  = 0.800;   // 5:4

    public static function has(string $slug): bool
    {
        return isset(self::MAP[$slug]);
    }

    /**
     * ["src" => …, "w" => …, "h" => …, "shift" => "62.4%", "dur" => "9.1s"]
     * or null when no screenshot exists (offline sites).
     */
    public static function get(string $slug): ?array
    {
        $m = self::MAP[$slug] ?? null;
        if (!$m) return null;

        $frame = $m[2] ? self::FRAME_APP : self::FRAME_SITE;
        $ratio = $m[1] / $m[0];                       // image height / width
        $shift = $ratio > $frame ? (1 - $frame / $ratio) : 0.0;

        // Constant perceived pan speed: long pages take longer, short ones do not
        // crawl. Clamped so nothing is instant and nothing outlasts a hover.
        $px  = $shift * $m[1];
        $dur = max(2.5, min(14.0, $px / 210));

        return [
            "src"   => "images/shots/{$m[3]}.webp",
            "w"     => $m[0],
            "h"     => $m[1],
            "shift" => round($shift * 100, 2) . "%",
            "dur"   => round($dur, 1) . "s",
        ];
    }

    /**
     * Same geometry, but the 1024px asset. A detail page renders the screenshot at
     * roughly 790px, where the card-sized 640px file would be upscaled and the UI
     * text inside the screenshot would go soft. App captures have no large variant —
     * a 480px phone screenshot is already wider than it is ever displayed.
     */
    public static function large(string $slug): ?array
    {
        $r = self::get($slug);
        if (!$r || (self::MAP[$slug][2] ?? false)) return $r;

        $scale = 1024 / $r["w"];
        $r["src"] = "images/shots/" . self::MAP[$slug][3] . "-lg.webp";
        $r["w"]   = 1024;
        $r["h"]   = (int) round($r["h"] * $scale);
        return $r;
    }

    private const MAP = [
        'amanlaw'                  => [640, 3921, false, 'aman-law-swiss-managed-legal-platform-website-screenshot'],
        'ant-assist'               => [640, 6000, false, 'ant-assist-uk-virtual-assistant-agency-website-screenshot'],
        'app-barmagly-customer'    => [480, 853, true, 'barmagly-order-food-android-app-screenshot'],
        'app-barmagly-pos'         => [480, 853, true, 'pos-barmagly-android-app-screenshot'],
        'app-klipp-salon'          => [480, 853, true, 'klipp-salon-booking-android-app-screenshot'],
        'app-omnixtrack-calls'     => [480, 993, true, 'omnixtrack-calls-android-app-screenshot'],
        'app-omnixtrack-crm'       => [480, 1041, true, 'omnixtrack-crm-android-app-screenshot'],
        'app-quran'                => [480, 807, true, 'holy-quran-barmagly-android-app-screenshot'],
        'app-tamem-delivery'       => [480, 853, true, 'tamem-delivery-android-app-screenshot'],
        'bankelarb'                => [640, 1618, false, 'bank-el-arab-arabic-financial-aid-guide-website-screenshot'],
        'barmagly-pos'             => [640, 3149, false, 'kassenta-cloud-multi-tenant-pos-system-website-screenshot'],
        'barmagly-salon'           => [640, 1820, false, 'klipp-ai-powered-salon-management-website-screenshot'],
        'barmagly-tech'            => [640, 3443, false, 'barmagly-swiss-licensed-software-house-website-screenshot'],
        'daamny'                   => [640, 3784, false, 'da3many-arabic-aid-and-grants-portal-website-screenshot'],
        'dr-mohamed-dental'        => [640, 3920, false, 'dr-mohamed-dental-clinic-booking-site-website-screenshot'],
        'drcembaysal'              => [640, 4377, false, 'dr-cem-baysal-istanbul-dental-clinic-website-screenshot'],
        'egysims'                  => [640, 1445, false, 'egysims-egyptian-flight-simulators-store-website-screenshot'],
        'gamestreet-q8'            => [640, 1790, false, 'game-street-kuwait-gaming-e-commerce-website-screenshot'],
        'hadiah-umrah'             => [640, 2838, false, 'hadiah-digital-umrah-service-app-website-screenshot'],
        'infinitywearsa'           => [640, 3793, false, 'infinity-wear-professional-sportswear-brand-website-screenshot'],
        'lotus-sharm'              => [640, 4451, false, 'lotus-sharm-sharm-el-sheikh-tourism-platform-website-screenshot'],
        'maeyn'                    => [640, 2409, false, 'maeyn-pilgrim-water-and-meals-supply-platform-website-screenshot'],
        'masaary'                  => [640, 1852, false, 'masaary-ai-career-skills-platform-website-screenshot'],
        'mossodor'                 => [640, 3435, false, 'mossodor-uk-premium-lighting-store-website-screenshot'],
        'ogs-academy'              => [640, 3244, false, 'ogs-academy-certified-industrial-training-website-screenshot'],
        'omnixtrack'               => [640, 3747, false, 'omnixtrack-arabic-multi-tenant-crm-website-screenshot'],
        'qinawy'                   => [640, 2499, false, 'qinawy-comprehensive-qena-local-directory-website-screenshot'],
        'quran-platform'           => [640, 400, false, 'quran-reader-free-ad-free-quran-platform-website-screenshot'],
        'rasa-lichfield'           => [640, 2478, false, 'rasa-lichfield-halal-pan-asian-restaurant-website-screenshot'],
        'salesman-marketing'       => [640, 1860, false, 'sales-man-stc-business-communication-website-screenshot'],
        'services-researcher'      => [640, 3031, false, 'services-researcher-academic-consultation-website-screenshot'],
        'skyteam-aviation'         => [640, 5206, false, 'skyteam-aviation-aviation-services-website-screenshot'],
        'standupstraight'          => [640, 2216, false, 'stand-up-straight-uk-posture-brand-website-screenshot'],
        'swissbridge-academy'      => [640, 5196, false, 'swiss-bridge-academy-e-learning-platform-website-screenshot'],
        'taffweed'                 => [640, 2699, false, 'taffweed-umrah-packages-and-booking-platform-website-screenshot'],
        'tamem-delivery'           => [640, 3189, false, 'tamem-delivery-upper-egypt-delivery-and-logistics-platform-website-screenshot'],
        'united-aviators'          => [640, 948, false, 'united-aviators-pilot-training-academy-website-screenshot'],
        'wasiila'                  => [640, 2338, false, 'wasiila-mecca-pilgrim-services-platform-website-screenshot'],
        'xappee'                   => [640, 3229, false, 'xappee-e-commerce-fulfillment-platform-website-screenshot'],
    ];
}
